# Generated by Django 3.2.7 on 2021-09-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='form_user',
            new_name='from_user',
        ),
    ]
