# Generated by Django 3.2.7 on 2021-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0002_auto_20210930_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='name_account',
            field=models.CharField(max_length=60, unique=True, verbose_name='Имя счета'),
        ),
    ]
